# Generated by Django 3.1 on 2020-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=50)),
                ('address', models.TextField(default='NULL')),
                ('phoneNumber', models.CharField(default='NULL', max_length=13)),
                ('postalCode', models.CharField(default='NULL', max_length=10)),
                ('username', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('deleted', models.CharField(default=0, max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
