# Generated by Django 3.1 on 2021-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
