# Generated by Django 3.1 on 2021-01-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0001_initial'),
    ]

    operations = [
    ]
