# Generated by Django 3.1 on 2021-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0002_auto_20210114_1347'),
    ]

    operations = [

    ]
