# Generated by Django 3.1 on 2021-02-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0002_auto_20210203_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
