# Generated by Django 3.0.9 on 2021-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0002_auto_20210116_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='namaOperator',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='imageCompany',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='profileOperator',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
