# Generated by Django 3.1 on 2020-11-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0003_auto_20201118_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlocation',
            name='id',
            field=models.CharField(default='NULL', max_length=5, primary_key=True, serialize=False),
        ),
    ]
