# Generated by Django 3.1 on 2021-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0003_auto_20210120_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='imageCompany',
            field=models.ImageField(blank=True, null=True, upload_to='images/company/'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='profileOperator',
            field=models.ImageField(blank=True, null=True, upload_to='images/operator/'),
        ),
    ]
