# Generated by Django 3.1 on 2021-01-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0003_auto_20210114_1352'),
    ]

    operations = [

    ]
