# Generated by Django 3.1 on 2021-02-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0003_auto_20210203_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('detail', models.CharField(choices=[('0', 'None'), ('1', 'Inbound'), ('2', 'Supplier Return'), ('3', 'Outbound'), ('4', 'Customer Return'), ('5', 'Borrowed'), ('6', 'Return Borrow')], default=0, max_length=2)),
                ('date', models.DateField(default='1000-10-10')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='avaible',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='borrowed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
