# Generated by Django 3.1 on 2021-01-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0004_auto_20210114_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='rw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rw',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='kota',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='rw',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
