# Generated by Django 3.1 on 2021-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0004_auto_20210208_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unplaced',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
