# Generated by Django 3.0.9 on 2021-01-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0004_auto_20210121_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('id_provinsi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.Province')),
            ],
        ),
    ]
