# Generated by Django 3.1 on 2020-11-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0004_auto_20201124_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='binlocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.binlocation'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('1', 'Open document'), ('2', 'Document ready'), ('3', 'Complete'), ('4', 'Returned')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='status',
            field=models.CharField(choices=[('0', 'unidentified'), ('1', 'avaible'), ('2', 'sold'), ('3', 'borrowed'), ('4', 'broken'), ('5', 'lost')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='status',
            field=models.CharField(choices=[('1', 'Open document'), ('2', 'Document ready'), ('3', 'Complete')], default=1, max_length=2),
        ),
    ]
