# Generated by Django 3.1 on 2021-01-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0004_auto_20210114_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
