# Generated by Django 3.1 on 2021-01-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0005_auto_20210115_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='binlocation',
            name='binlocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
