# Generated by Django 3.1 on 2021-02-08 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0005_item_unplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemin',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.item'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.user'),
        ),
        migrations.AddField(
            model_name='log',
            name='userGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.usergroup'),
        ),
        migrations.AlterField(
            model_name='log',
            name='detail',
            field=models.CharField(choices=[('0', 'None'), ('1', 'In'), ('2', 'Move'), ('3', 'Outbound'), ('4', 'Customer Return'), ('5', 'Borrowed'), ('6', 'Return Borrow')], default=0, max_length=2),
        ),
    ]
