# Generated by Django 3.0.9 on 2021-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0005_auto_20210122_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='id_provinsi',
            new_name='provinsi',
        ),
    ]
