# Generated by Django 3.1 on 2020-12-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0006_auto_20201125_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
