# Generated by Django 3.1 on 2021-01-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0006_auto_20210116_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='binlocation',
        ),
        migrations.AlterField(
            model_name='binlocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
