# Generated by Django 3.1 on 2021-01-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0007_auto_20210116_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='binlocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.binlocation'),
        ),
        
    ]
