# Generated by Django 3.1 on 2020-12-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0010_auto_20201213_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='returndata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.supplierreturndata'),
        ),
    ]
