# Generated by Django 3.1 on 2020-12-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0011_itemdata_returndata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='returnData',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.supplierreturndata'),
        ),
    ]
