# Generated by Django 3.1 on 2021-01-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0012_auto_20201226_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
