# Generated by Django 3.0.9 on 2021-01-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0012_auto_20201226_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbound',
            name='address',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='name',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='outbound',
            name='postalCode',
        ),
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='districts',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='province',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='districts',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='districts',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='city',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='districts',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='province',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(default='NULL', max_length=50)),
                ('address', models.TextField(default='NULL')),
                ('phoneNumber', models.CharField(default='NULL', max_length=13)),
                ('postalCode', models.CharField(default='NULL', max_length=10)),
                ('districts', models.CharField(default='NULL', max_length=50)),
                ('city', models.CharField(default='NULL', max_length=50)),
                ('province', models.CharField(default='NULL', max_length=50)),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('deleted', models.CharField(default=0, max_length=1)),
                ('email', models.CharField(default='NULL', max_length=50)),
                ('userGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.UserGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='outbound',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WMS.Customer'),
        ),
    ]
