# Generated by Django 3.1 on 2021-01-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0013_subcategory_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='active',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
